#!/bin/sh
## purpose: controll OTA
## license: GPLv3+, http://www.gnu.org/licenses/gpl-3.0.html
## author: Jan Sperling , 2017

sd_mountdir="/tmp/sd"
if [ -r "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh" ]; then
  . "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh"
else
  echo "Unable to load basic functions"
  exit 1
fi

disable_ota() {
  echo "Disabling OTA"
  disable_binary "/mnt/data/miio_ota/miio_ota" "miio_ota"
  if pgrep restartd >/dev/null; then
    /mnt/data/imi/imi_init/S99restartd restart
  fi
}

enable_ota() {
  if [ -f "${sd_mountdir}/mijia-720p-hack/scripts/.pre-ota.sh" ] &&
     ! mount | grep -q /mnt/data/miio_ota/pre-ota.sh; then
    echo "Imporve OTA script"
    mount --bind "${sd_mountdir}/mijia-720p-hack/scripts/.pre-ota.sh" /mnt/data/miio_ota/pre-ota.sh
  fi
  #/mnt/data/imi/imi_init/S95miio_ota
  enable_binary "/mnt/data/miio_ota/miio_ota" "miio_ota"
  if pgrep restartd >/dev/null; then
    /mnt/data/imi/imi_init/S99restartd restart
  fi
}

case "$1" in
  start)
    disable_ota
    ;;
  stop)
    enable_ota
    ;;
  status)
    if pgrep miio_ota; then
      echo "OTA not disabled"
      return 3
    else
      echo "OTA disabled"
      return 0
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|status}"
    exit 1
    ;;
esac

exit $?

