#!/bin/sh
## purpose: Init script for dropbear SSH server
## license: GPLv3+, http://www.gnu.org/licenses/gpl-3.0.html
## author: Jan Sperling , 2017

sd_mountdir="/tmp/sd"
if [ -r "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh" ]; then
  . "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh"
else
  echo "Unable to load basic functions"
  exit 1
fi

NAME="dropbear"
DESC="SSH server"
DAEMON="${sd_mountdir}/mijia-720p-hack/bin/${NAME}"
DAEMON_OPTS="-R -p 22"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="${LOGDIR}/${NAME}.log"

check_daemon_bin "${DAEMON}" "${DESC}"

case "$1" in
  start)
    if [ ! -d /etc/dropbear ]; then
      mkdir -p /etc/dropbear
    fi
    ## Security Purpose: recover previoys RSA keys from SDCARD
    if [ -s "${sd_mountdir}/mijia-720p-hack/etc/dropbear_ecdsa_host_key" ]; then 
      cp "${sd_mountdir}/mijia-720p-hack/etc/dropbear_ecdsa_host_key" /etc/dropbear
    fi

    start_daemon

    ## Security Purpose: Save the keys in the SDCARD
    if [ ! -s "${sd_mountdir}/mijia-720p-hack/etc/dropbear_ecdsa_host_key" ] &&
       [ -s /etc/dropbear/dropbear_ecdsa_host_key ]; then
      cp /etc/dropbear/dropbear_ecdsa_host_key "${sd_mountdir}/mijia-720p-hack/etc/"
    fi
    ;;
  stop)
    stop_daemon
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  status)
    status_daemon
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit $?
