#!/bin/sh
## purpose: Init script for lighttpd web server
## license: GPLv3+, http://www.gnu.org/licenses/gpl-3.0.html
## author: Jan Sperling , 2017

sd_mountdir="/tmp/sd"
if [ -r "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh" ]; then
  . "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh"
else
  echo "Unable to load basic functions"
  exit 1
fi

NAME="lighttpd"
DESC="web server"
DAEMON="${sd_mountdir}/mijia-720p-hack/bin/${NAME}"
DAEMON_OPTS="-f ${sd_mountdir}/mijia-720p-hack/etc/lighttpd.conf"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="${LOGDIR}/${NAME}.log"

check_daemon_bin "${DAEMON}" "${DESC}"

case "$1" in
  start)
    if [ ! -d "${sd_mountdir}/mijia-720p-hack/tmp" ]; then
      mkdir -p "${sd_mountdir}/mijia-720p-hack/tmp"
    fi
    start_daemon
    ;;
  stop)
    stop_daemon
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  status)
    status_daemon
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit $?
